"use client";
import { useState } from "react";
import Link from "next/link";
import { SiteShell } from "../components/SiteShell";

const services = [
  { name: "UI/UX Design", intro: "Interface yang membuat keputusan terasa lebih mudah.", bullets: ["UX research and customer journey", "Wireframe, prototype, and design system", "Website, dashboard, and mobile app UI"], plans: [["Basic", "Focused design sprint", "1 key flow, wireframes, visual direction"], ["Intermediate", "Product experience", "Core flows, clickable prototype, handoff"], ["Advanced", "Scalable design system", "Research, full experience, design system"]] },
  { name: "Web Development", intro: "Website cepat, jelas, dan siap menjadi mesin konversi.", bullets: ["Company profile and conversion landing pages", "Responsive front-end and CMS-ready build", "Analytics, SEO foundations, and integrations"], plans: [["Basic", "Launch page", "One high-impact landing page"], ["Intermediate", "Growth website", "Multi-page site with analytics"], ["Advanced", "Digital platform", "Custom portal, integrations, ongoing support"]] },
  { name: "Digital Marketing", intro: "Campaign dengan pesan yang konsisten dari awareness hingga action.", bullets: ["Campaign strategy and channel planning", "Content direction and paid media setup", "Reporting, experimentation, and optimization"], plans: [["Basic", "Campaign starter", "One channel and a clear launch plan"], ["Intermediate", "Growth campaign", "Multi-channel content and optimisation"], ["Advanced", "Performance engine", "Full-funnel campaign and weekly iteration"]] },
  { name: "SEO", intro: "Organic visibility built around what your audience is searching for.", bullets: ["Technical and content opportunity audit", "Keyword map and on-page optimisation", "Content briefs, reporting, and growth roadmap"], plans: [["Basic", "SEO foundation", "Audit and priority fixes"], ["Intermediate", "SEO momentum", "Content plan and monthly optimisation"], ["Advanced", "Organic growth", "Technical, content, and authority programme"]] },
  { name: "Branding", intro: "A distinct identity that aligns what you say, show, and deliver.", bullets: ["Positioning, audience, and competitive lens", "Naming, messaging, and verbal identity", "Visual identity, guidelines, and rollout"], plans: [["Basic", "Brand clarity", "Positioning workshop and direction"], ["Intermediate", "Brand identity", "Messaging and visual identity system"], ["Advanced", "Brand transformation", "Strategy, identity, guideline, launch support"]] },
];

export default function Services(){
  const [active,setActive]=useState(0); const service=services[active];
  return <SiteShell><section className="inner-hero compact"><div className="wrap"><p className="eyebrow">SERVICES</p><h1>One partner for the<br/><i>whole digital picture.</i></h1><p>Choose a focused engagement or combine disciplines into one connected growth system.</p></div></section><section className="wrap section service-explorer"><div className="service-tabs" role="tablist">{services.map((item,i)=><button key={item.name} className={i===active?"active":""} onClick={()=>setActive(i)} role="tab" aria-selected={i===active}>{item.name}</button>)}</div><div className="service-detail"><div><p className="eyebrow">0{active+1} / {service.name}</p><h2>{service.intro}</h2><ul>{service.bullets.map(b=><li key={b}>{b}</li>)}</ul></div><div className="package-grid">{service.plans.map(([name,tag,copy],i)=><article key={name} className={i===1?"featured":""}><p>{name}</p><h3>{tag}</h3><span>{copy}</span><Link href={`/consultation?service=${encodeURIComponent(service.name)}&package=${name}`}>Discuss this plan -&gt;</Link></article>)}</div></div></section><section className="callout"><div className="wrap"><p className="eyebrow light">CUSTOM, NOT COOKIE-CUTTER</p><h2>Need a combination built around your business?</h2><Link href="/consultation" className="button gold">Design your scope -&gt;</Link></div></section></SiteShell>;
}
