"use client";
import { FormEvent, useState } from "react";
import { SiteShell } from "../components/SiteShell";

export default function Consultation() {
  const [ready, setReady] = useState(false);
  const submit = (event: FormEvent) => { event.preventDefault(); setReady(true); };
  return <SiteShell><section className="inner-hero compact"><div className="wrap"><p className="eyebrow">MARI BEKERJA SAMA</p><h1>Bawa peluang Anda.<br/>Kita rapikan <i>arahnya.</i></h1><p>Ceritakan konteks yang penting. Kami membantu UMKM dan startup memulai dari masalah yang paling perlu dibereskan, bukan dari penawaran yang asal jadi.</p></div></section><section className="wrap section consultation-layout">{ready ? <div className="form-success"><p className="eyebrow">BRIEF SUDAH SIAP</p><h2>Terima kasih. Mari lanjutkan percakapannya.</h2><p>Ringkasan brief Anda sudah selesai diisi. Saat ini formulir belum mengirim data ke server; gunakan jalur konsultasi resmi Diksilab untuk membahas kebutuhan Anda bersama tim.</p><button className="button gold" onClick={() => setReady(false)}>Isi brief lagi</button></div> : <form className="work-form" onSubmit={submit}><div className="form-intro"><p className="eyebrow">BRIEF PROYEK</p><h2>Mulai dari yang paling penting.</h2><p>Kolom bertanda * membantu kami memahami konteks dan menyiapkan obrolan awal yang lebih relevan.</p></div><div className="form-fields"><label>Nama *<input required placeholder="Nama Anda"/></label><label>Email kerja *<input required type="email" placeholder="nama@perusahaan.com"/></label><label>Nomor WhatsApp<input type="tel" placeholder="+62 ..."/></label><label>Perusahaan / brand *<input required placeholder="Nama bisnis Anda"/></label><label>Website atau kanal utama<input type="url" placeholder="https://"/></label><label>Apa yang Anda butuhkan? *<select required defaultValue=""><option value="" disabled>Pilih layanan</option><option>UI/UX & Website</option><option>Performance Marketing</option><option>SEO</option><option>Branding & Rebranding</option><option>Proyek pertumbuhan terintegrasi</option></select></label><label>Estimasi investasi<select defaultValue=""><option value="" disabled>Pilih rentang</option><option>Di bawah Rp25 juta</option><option>Rp25 - 75 juta</option><option>Rp75 - 150 juta</option><option>Rp150 juta+</option><option>Butuh arahan</option></select></label><label>Target waktu<select defaultValue=""><option value="" disabled>Pilih target waktu</option><option>Dalam 1 bulan</option><option>1 - 3 bulan</option><option>Lebih dari 3 bulan</option><option>Masih mengeksplorasi</option></select></label><label className="full">Seperti apa hasil proyek yang Anda harapkan? *<textarea required rows={5} placeholder="Tujuan, audiens, tantangan saat ini, dan konteks lain yang berguna."/></label><label className="consent full"><input required type="checkbox"/> Saya setuju Diksilab menggunakan informasi ini untuk menanggapi permintaan saya.</label><button className="button gold" type="submit">Siapkan brief proyek</button></div></form>}</section></SiteShell>;
}
