"use client";
import { useMemo, useState } from "react";

const coreQuestions = [
  ["Strategi Brand", "Seberapa jelas target market utama bisnis Anda?", ["Belum tahu targetnya secara spesifik", "Sudah ada gambaran, tapi masih umum", "Sudah jelas dan terdokumentasi"]],
  ["Strategi Brand", "Apakah brand Anda punya alasan kuat untuk dipilih dibanding kompetitor?", ["Masih terasa mirip dengan yang lain", "Sudah ada pembeda, tapi belum konsisten", "Pembedanya jelas dan mudah dijelaskan"]],
  ["Strategi Brand", "Apakah pesan utama brand Anda terasa konsisten di semua touchpoint?", ["Pesan masih berubah-ubah", "Sudah mulai selaras di beberapa kanal", "Pesannya konsisten dan mudah diingat"]],
  ["Identitas Visual", "Apakah tampilan brand Anda terlihat konsisten dan profesional?", ["Belum punya arah visual yang jelas", "Sudah ada elemen dasar, tapi belum rapi", "Sudah konsisten di seluruh materi utama"]],
  ["Identitas Visual", "Apakah logo, warna, dan tipografi benar-benar mencerminkan karakter brand?", ["Belum terasa mewakili brand", "Cukup mewakili, tapi belum kuat", "Sangat mewakili dan mudah dikenali"]],
  ["Identitas Visual", "Apakah tim Anda punya panduan visual yang mudah dipakai?", ["Belum ada panduan", "Ada beberapa contoh, tapi belum lengkap", "Ada panduan yang rapi dan dipakai bersama"]],
  ["Kehadiran Digital", "Apakah website atau kanal utama Anda langsung menjelaskan apa yang Anda tawarkan?", ["Masih membingungkan", "Sudah cukup jelas, tapi perlu dirapikan", "Langsung jelas dalam beberapa detik"]],
  ["Kehadiran Digital", "Apakah pengunjung mudah menemukan langkah berikutnya yang perlu dilakukan?", ["Belum ada alur yang jelas", "Ada beberapa CTA, tapi saling bersaing", "Ada satu alur utama yang jelas"]],
  ["Kehadiran Digital", "Apakah kehadiran digital Anda nyaman digunakan dari ponsel?", ["Masih banyak kendala di mobile", "Sudah berfungsi, tetapi belum optimal", "Cepat, rapi, dan nyaman di mobile"]],
  ["Konten & Sosial", "Apakah Anda punya pilar konten yang jelas untuk berbicara dengan audiens?", ["Masih posting secara acak", "Sudah ada tema, tapi belum konsisten", "Pilar konten jelas dan dijalankan rutin"]],
  ["Konten & Sosial", "Apakah konten Anda membantu audiens memahami nilai brand Anda?", ["Konten belum punya arah yang jelas", "Ada konten yang relevan, tapi belum merata", "Konten konsisten membangun kepercayaan"]],
  ["Konten & Sosial", "Apakah Anda punya proses untuk membuat konten tanpa selalu mulai dari nol?", ["Belum ada proses tetap", "Sudah ada proses sederhana", "Punya sistem yang bisa diulang dan diukur"]],
  ["Funnel Marketing", "Apakah Anda tahu perjalanan calon pelanggan dari mengenal sampai membeli?", ["Belum benar-benar dipetakan", "Sudah ada gambaran dasar", "Sudah punya alur dan prioritas yang jelas"]],
  ["Funnel Marketing", "Apakah follow-up setelah orang tertarik sudah berjalan dengan rapi?", ["Belum ada alur follow-up", "Masih dilakukan manual dan tidak konsisten", "Sudah ada alur follow-up yang terarah"]],
  ["Funnel Marketing", "Apakah Anda bisa melihat bagian mana yang membuat calon pelanggan berhenti?", ["Belum bisa melihatnya", "Ada data dasar, tapi belum rutin ditinjau", "Data dan insight dipakai untuk memperbaiki alur"]],
  ["Iklan & Performa", "Apakah campaign iklan Anda punya tujuan, target, dan metrik yang jelas?", ["Iklan masih coba-coba", "Sudah punya tujuan, tapi belum terukur rapi", "Tujuan dan metrik dipantau dengan jelas"]],
  ["Iklan & Performa", "Apakah Anda rutin menguji creative, targeting, atau landing page?", ["Jarang melakukan pengujian", "Kadang-kadang menguji", "Pengujian jadi bagian dari rutinitas"]],
  ["Iklan & Performa", "Apakah Anda tahu campaign mana yang membawa lead atau penjualan berkualitas?", ["Belum bisa dilacak", "Sudah ada laporan dasar", "Atribusi dan kualitas hasilnya jelas"]],
] as const;

const advancedQuestions = [
  ["Tujuan bisnis", "Apakah target pertumbuhan 90 hari Anda sudah punya angka yang ingin dicapai?", ["Belum ada target angka", "Sudah ada target, tapi belum dipecah", "Target jelas dan punya indikator"]],
  ["Penawaran", "Seberapa siap penawaran utama Anda untuk dikomunikasikan atau dijual?", ["Nilai dan paket belum rapi", "Sudah ada, tapi masih perlu dipertajam", "Nilai, bukti, dan paketnya jelas"]],
  ["Aset", "Apakah Anda punya materi dan bukti yang cukup untuk mendukung campaign?", ["Aset masih sangat terbatas", "Sudah ada sebagian", "Aset siap pakai dan terus diperbarui"]],
  ["Tim", "Apakah ada orang yang jelas bertanggung jawab menjalankan rencana?", ["Belum ada pemilik yang jelas", "Ada, tetapi kapasitasnya terbatas", "Tanggung jawab dan ritmenya jelas"]],
  ["Data", "Apakah Anda rutin meninjau angka untuk mengambil keputusan?", ["Masih mengandalkan perasaan", "Sudah cek angka sesekali", "Ada ritme review dan keputusan"]],
  ["Eksekusi", "Apakah Anda punya ruang waktu dan anggaran untuk menjalankan prioritas?", ["Belum ada ruang yang cukup", "Ada, tetapi belum dialokasikan jelas", "Waktu dan anggaran sudah disiapkan"]],
] as const;

const pillars = ["Strategi Brand", "Identitas Visual", "Kehadiran Digital", "Konten & Sosial", "Funnel Marketing", "Iklan & Performa"];

const playbooks: Record<string, string[]> = {
  "Strategi Brand": ["Tulis ulang target market dan masalah utama yang ingin Anda selesaikan.", "Pilih satu pembeda yang paling kuat untuk jadi pesan utama.", "Pakai pesan itu di website, profil, dan materi campaign."],
  "Identitas Visual": ["Kumpulkan semua aset visual yang sedang dipakai.", "Tentukan warna, tipografi, dan gaya visual yang paling relevan.", "Buat panduan singkat agar eksekusi tim tetap konsisten."],
  "Kehadiran Digital": ["Rapikan pesan utama di layar pertama website atau profil.", "Pastikan hanya ada satu CTA utama di setiap halaman penting.", "Cek kembali pengalaman mobile dari klik pertama sampai inquiry."],
  "Konten & Sosial": ["Pilih tiga pilar konten yang paling dekat dengan kebutuhan audiens.", "Susun ide konten untuk empat minggu ke depan.", "Gunakan format yang sama untuk membangun pengenalan dan kepercayaan."],
  "Funnel Marketing": ["Petakan perjalanan dari konten atau iklan sampai menjadi lead.", "Rapikan follow-up pertama dan tentukan respons maksimalnya.", "Lihat titik yang paling sering membuat calon pelanggan berhenti."],
  "Iklan & Performa": ["Tentukan satu tujuan utama sebelum menambah budget iklan.", "Rapikan tracking dan definisi lead berkualitas.", "Uji satu creative atau targeting dalam satu waktu agar belajarnya jelas."],
};

function levelFor(score: number) { return score > 76 ? ["Siap Tumbuh", "Fondasinya kuat. Saatnya memperbesar dampak."] : score > 52 ? ["Mulai Terarah", "Banyak dasarnya sudah ada. Tinggal rapikan prioritas."] : ["Perlu Dirapikan", "Mulai dari fondasi yang paling memengaruhi hasil."]; }

export function Audit({ expanded = false }: { expanded?: boolean }) {
  const [step, setStep] = useState(0); const [answers, setAnswers] = useState<number[]>([]); const [advanced, setAdvanced] = useState(false); const [advancedStep, setAdvancedStep] = useState(0); const [advancedAnswers, setAdvancedAnswers] = useState<number[]>([]); const [advancedDone, setAdvancedDone] = useState(false);
  const score = useMemo(() => answers.length ? Math.round((answers.reduce((a,b) => a + b, 0) / (coreQuestions.length * 2)) * 100) : 0, [answers]);
  const totals = useMemo(() => pillars.map(pillar => ({ pillar, value: answers.reduce((sum, answer, index) => coreQuestions[index]?.[0] === pillar ? sum + answer : sum, 0) })), [answers]);
  const focus = totals.length ? [...totals].sort((a,b) => a.value - b.value)[0].pillar : pillars[0]; const [level, levelText] = levelFor(score); const plan = playbooks[focus];
  function reset() { setStep(0); setAnswers([]); setAdvanced(false); setAdvancedStep(0); setAdvancedAnswers([]); setAdvancedDone(false); }
  function pick(value: number) { const next = [...answers, value]; setAnswers(next); if (step < coreQuestions.length - 1) setStep(step + 1); }
  function pickAdvanced(value: number) { const next = [...advancedAnswers, value]; setAdvancedAnswers(next); if (advancedStep === advancedQuestions.length - 1) setAdvancedDone(true); else setAdvancedStep(advancedStep + 1); }
  const coreDone = answers.length === coreQuestions.length;
  if (advanced && !advancedDone) { const [category, question, choices] = advancedQuestions[advancedStep]; return <div className={`audit-card audit-expanded ${expanded ? "audit-advanced-card" : ""}`}><div className="audit-kicker"><p className="eyebrow">AUDIT LANJUTAN</p><span>Lebih dalam, tetap singkat</span></div><div className="audit-progress"><span>{String(advancedStep + 1).padStart(2,"0")} / {advancedQuestions.length}</span><i><b style={{width:`${((advancedStep + 1) / advancedQuestions.length) * 100}%`}} /></i></div><div className="audit-question-top"><p className="audit-category">{category}</p><small>Melengkapi hasil audit utama Anda.</small></div><h3>{question}</h3><div className="answers">{choices.map((answer,index) => <button key={answer} onClick={() => pickAdvanced(index)}><b>0{index + 1}</b>{answer}<span>→</span></button>)}</div>{advancedStep > 0 && <button className="audit-back" onClick={() => { setAdvancedStep(advancedStep - 1); setAdvancedAnswers(advancedAnswers.slice(0,-1)); }}>← Kembali</button>}</div>; }
  if (coreDone) { const advancedScore = advancedAnswers.length ? Math.round((advancedAnswers.reduce((a,b) => a + b, 0) / (advancedQuestions.length * 2)) * 100) : null; return <div className={`audit-card result ${expanded ? "audit-expanded-result" : ""}`}><div className="audit-result-hero"><div className="audit-score-orb"><strong>{score}</strong><span>/100</span></div><div><p className="eyebrow">HASIL AUDIT ANDA</p><p className="audit-level">{level}</p><h3>{levelText}</h3><p>Fokus terbaik untuk Anda sekarang adalah <b>{focus}</b>.</p></div></div><div className="audit-priority"><p className="eyebrow">RENCANA 30 HARI</p><h4>Tiga langkah untuk mulai bergerak</h4><ol>{plan.map((item, index) => <li key={item}><b>0{index + 1}</b><span>{item}</span></li>)}</ol></div><div className="audit-pillars audit-pillars-rich">{totals.map(({pillar,value}) => { const valueScore = Math.round(value / 6 * 100); return <div key={pillar} className={pillar === focus ? "priority" : ""}><span>{pillar}</span><strong>{valueScore}</strong><i><b style={{width:`${valueScore}%`}}/></i></div>; })}</div>{advancedDone && <div className="audit-advanced-summary"><p className="eyebrow">KESIAPAN EKSEKUSI</p><b>{advancedScore}<small>/100</small></b><span>{advancedScore && advancedScore > 65 ? "Anda cukup siap untuk mengeksekusi rencana ini secara konsisten." : "Sebelum mempercepat eksekusi, rapikan kapasitas tim, aset, dan ritme review."}</span></div>}<div className="audit-result-actions">{!advancedDone && <button onClick={() => setAdvanced(true)} className="button gold">Lanjut ke audit mendalam →</button>}<a href={`/consultation?focus=${encodeURIComponent(focus)}`} className="button outline">Bahas hasil ini →</a><button onClick={reset} className="reset">Ulangi audit</button></div><p className="audit-privacy">Hasil ini hanya dihitung di browser Anda. Tidak ada data yang disimpan atau dikirim ke CRM.</p></div>; }
  const [category, question, choices] = coreQuestions[step]; return <div className={`audit-card ${expanded ? "audit-expanded" : ""}`}><div className="audit-kicker"><p className="eyebrow">AUDIT DASAR</p><span>± 5 menit</span></div><div className="audit-progress"><span>{String(step + 1).padStart(2,"0")} / {coreQuestions.length}</span><i><b style={{width:`${((step + 1) / coreQuestions.length) * 100}%`}} /></i></div><div className="audit-question-top"><p className="audit-category">{category}</p>{expanded && <small>Jawab sesuai kondisi bisnis Anda sekarang, ya.</small>}</div><h3>{question}</h3><div className="answers">{choices.map((answer,index) => <button key={answer} onClick={() => pick(index)}><b>0{index + 1}</b>{answer}<span>→</span></button>)}</div>{step > 0 && <button className="audit-back" onClick={() => { setStep(step - 1); setAnswers(answers.slice(0,-1)); }}>← Kembali</button>}</div>;
}
