import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteShell } from "../../components/SiteShell";
const content:Record<string,{topic:string,title:string,dek:string,body:string[]}>={
  "brand-signal":{topic:"STRATEGY",title:"How to turn a brand promise into a digital signal",dek:"A brand promise only earns value when people can recognise it in the moments that matter.",body:["Start with the tension your customer feels before they choose. A useful promise is not a description of your company; it is a clear commitment to change that tension.","Then make the commitment visible. It should guide the headline, the proof you choose, the way a page moves, and the call to action. Consistency does not mean every channel looks identical. It means each channel makes the same idea easier to recognise.","Finally, measure the signal. Are people taking the intended next step? Are sales conversations using the language you introduced? The strongest brands adjust the execution while protecting the promise."]},
  "website-clarity":{topic:"EXPERIENCE",title:"Five signs your website is making visitors work too hard",dek:"The most common conversion barrier is not a lack of content. It is a lack of direction.",body:["Visitors should understand what you offer, who it is for, and what to do next without translating your language. If the first screen needs a long explanation, the message is carrying too much weight.","Use hierarchy to make decisions easy. One primary action, proof close to the claim it supports, and deliberate grouping of related information will do more than adding another paragraph.","Clarity also needs to survive the handoff to mobile. Review your pages at the smallest likely screen size and remove anything that makes the action harder to find."]},
  "growth-system":{topic:"GROWTH",title:"Why the best growth campaigns start before the first ad",dek:"Media works harder when the destination and message are designed as one system.",body:["A campaign begins with an audience decision: who is most ready to act, what they need to believe, and why they should choose you now. The creative is a delivery mechanism for that decision.","Before spending, check the landing experience. Does it continue the message? Does it offer the next small commitment? Is measurement ready to tell you what changed? These questions keep early learning useful.","Treat every campaign as a loop. Message, page, analytics, and follow-up should inform the next iteration rather than operating as separate projects."]}
};
export default async function Article({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const article=content[slug];if(!article)notFound();return <SiteShell><article className="article-post"><div className="wrap"><Link href="/articles" className="back-link">&lt;- All insights</Link><p className="eyebrow">{article.topic}</p><h1>{article.title}</h1><p className="article-dek">{article.dek}</p><div className="article-body">{article.body.map(p=><p key={p}>{p}</p>)}</div><div className="article-next"><p>Ready to apply this to your business?</p><Link className="button gold" href="/consultation">Talk to our team -&gt;</Link></div></div></article></SiteShell>}
